config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag_list', to: 'posts#index', as: :tag_list
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :posts do
  	resources :comments
    collection { post :import }
  end
  resources :export

  root "posts#index"
  get '/list', to: 'posts#list'
  get '/order', to: 'orders#index'
  get '/about', to: 'pages#about'
  get '/change/:id', to: 'posts#status', as: :status

  #Error Pages
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_taggable # Alias for acts_as_taggable_on :tags
	acts_as_taggable_on :tag_list
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates :title, uniqueness: true
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true, length: { minimum: 10 }
	validates :status, presence: true
	scope :status_active, -> {where(status: 'active')}

	self.per_page = 10
	

	def self.to_csv(post)
		CSV.generate do |csv|
			csv << column_names
			all.each do |post|
				csv << post.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			post = find_by_id(row["id"]) || new
			post.attributes = row.to_hash.slice(*Post.attribute_names())
			post.save!
		end
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
			when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
	  		when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	  		when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	  		else raise "Unknown file type: #{file.original_filename}"
  		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/No-Avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :username, :password, :password_confirmation)}
	    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :avatar)}
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		Notifier.confirmation(@post).deliver
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  end

  def unprocessable
  end

  def internal_server_error
  end
end

app/controllers/export_controller.rb
class ExportController < ApplicationController
	def show
		@post = Post.find(params[:id])
		respond_to do |format|
		  format.xls
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		if params[:tag_list]
			@posts = Post.paginate(:page => params[:page], :per_page => 10).tagged_with(params[:tag_list]).order('created_at DESC').status_active
		else
			@posts = Post.paginate(:page => params[:page], :per_page => 10).order('created_at DESC').status_active
		end
		respond_to do |format|
		  format.html
		  format.csv { send_data text: @posts.to_csv }
		  format.xls #{ send_data text: @posts.to_csv(col_sep: "\t") }
		  format.js
		end
	end
	
	def import
		Post.import(params[:file])
		redirect_to root_url, notice: "Posts imported."
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body, :status))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	def list
		if params[:tag_list]
			@posts = current_user.posts.paginate(:page => params[:page], :per_page => 10).tagged_with(params[:tag_list]).order('created_at DESC')
		else
			@posts = current_user.posts.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
		end
		respond_to do |format|
		  format.html
		end
	end

	def status
		@post = Post.find(params[:id])
		if @post.status == "off"
			@post.update(:status => "active")
		else
			@post.update(:status => "off")
		end
		redirect_to list_path, notice: "Post status has changed to " + @post.status
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :tag_list, :status)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	def new
		super
	end
  def create
    @user = User.find_by_username(params[:username])
    if @user != nil
    	redirect_to root_path
    else
        super
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
	def check_page
		if current_page?(root_path)
			"All Posts"
		elsif current_page?(about_path)
			"About"
		else
			link_to 'Back to All Posts', root_path
		end
	end

	def check_status_login
		if user_signed_in?
			render 'layouts/layouts_render/profile'
		else
			render 'layouts/layouts_render/login'
		end
	end

	def permit(post)
		if user_signed_in?
			if post.user.email == current_user.email
				render "posts/permit"
			else
				""	
			end
		else
			""
		end
	end

	def comment_form
		if user_signed_in?
			"<h3>Add a comment:</h3>".html_safe
			render "comments/form"
		else
			"<div class= 'alert'>
				You need sign in before add a comment
			</div>".html_safe
		end
	end

	def delete_action(comment)
		if user_signed_in?
			link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: "Are you sure?"}
		else
			""
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<!-- Render Sidebar -->
	<%= render 'layouts/layouts_render/side' %>
	
	<div id="main_content">
	
		<!-- Render Header -->
		<%= render 'layouts/layouts_render/header' %>

		<!-- Render Message -->
		<%= render 'layouts/layouts_render/message' %>
		
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/layouts_render/_header.html.erb
<div id="header">
	<p>
		<!-- Check this function in application_helper.rb -->
		<%= check_page %>
	</p>

	<!-- Check this function in application_helper.rb -->
	<%= check_status_login %>
</div>

app/views/layouts/layouts_render/_login.html.erb
<div class="buttons">
	<%= link_to "Login", new_user_session_path, :class => 'sign_in button'  %>
</div>

app/views/layouts/layouts_render/_message.html.erb
<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert") %>
<% end %>

app/views/layouts/layouts_render/_profile.html.erb
<div class="buttons">
	<div id="avatar">
		<%= image_tag(current_user.avatar.url(:thumb)) %>
	</div>
	<%= link_to "My Posts", list_path, :class => 'button' %>
	<%= link_to "New Post", new_post_path, :class => 'button' %>
	<%= link_to "#{current_user.username}", edit_user_registration_path, :class => 'button' %>
	<%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'button' %>
</div>

app/views/layouts/layouts_render/_side.html.erb
<div id="sidebar">
	<div id="logo">
		<%= image_tag "logo.png", class: "logo" %>
	</div>
	<ul>
		<li class="category">Website</li>
		<li><%= link_to "Blog", root_path %></li>
		<li><%= link_to "About", about_path %></li>
	</ul>
	<ul>
		<li class="category">Social</li>
		<li><a href="https://twitter.com/A_darmawann">Twitter</a></li>
		<li><a href="https://www.facebook.com/">Facebook</a></li>
		<li><a href="https://github.com/asepasdar">Github</a></li>
		<li><a href="mailto:a.darmawan93@gmail.com">Email</a></li>
	</ul>	
</div>

app/views/list/index.html.erb
<div class="col-lg-12">
	<h2>My Posts</h2>
	<div class="table-responsive">
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Post</th>
					<th>Tags</th>
					<th>Submitted</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% @posts.each do |post| %>
		        	<tr>
						<td><%= post.title %></td>
						<td><%= post.tag_list.map { |t| link_to t, "#" }.join(', ').html_safe %></td>
						<td><%= time_ago_in_words(post.created_at) %> Ago </td>
						<td><%= link_to post.status, status_path(post.id), class: "action" %></td>
						<td>
							<%= link_to 'Edit', edit_post_path(post), class: "action" %>
							| <%= link_to 'Delete', post_path(post), method: :delete, data:{confirm: 'Are You Sure?'}, class: "action" %>
						</td>
					</tr>
				<% end %>
			</tbody>

		</table>
	</div>
</div>

app/views/notifier/confirmation.html.erb
<h1>Notification</h1>
Hi <%= @owner %>,<br>
You have received a comment on your article "<%= @post.title %>"<br>
<br>

<p>
  <%= @commenter.name %> : "<%= @commenter.body %>"
</p>
<p><%= link_to "Check This Out !!!",  post_url(@post) %></p>

app/views/notifier/confirmation.text.erb
Notifier#confirmation

<%= @greeting %>, find me in app/views/notifier/confirmation.text.erb

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image" class="div_image">
		<%= image_tag "profile.jpg" %>
	</div>

	<div id="content" class="div_des">
		<h1>Hi, I'm Asep Darmawan</h1>
		<p>I'm newbie in Rails, but i tried my best</p>
		<p>This week i built a blog in Rails 4, i'm actually on the demo application right now. Cool stuff, right!!!</p>
		<p>Find me on twitter <a href="http://twitter.com/A_darmawann">@a_darmawann</a> or on facebook <a href="https://www.facebook.com/asep.darmawan.391">Asep Darmawann</a></p>
	</div>
</div>