config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag_list', to: 'posts#index', as: :tag_list
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :posts do
  	resources :comments
    collection { post :import }
  end
  resources :export

  root "posts#index"
  get '/list', to: 'posts#list'
  get '/order', to: 'orders#index'
  get '/about', to: 'pages#about'
  get '/change/:id', to: 'posts#status', as: :status

  #Error Pages
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_taggable # Alias for acts_as_taggable_on :tags
	acts_as_taggable_on :tag_list
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates :title, uniqueness: true
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true, length: { minimum: 10 }
	validates :status, presence: true
	scope :status_active, -> {where(status: 'active')}

	self.per_page = 10
	

	def self.to_csv(post)
		CSV.generate do |csv|
			csv << column_names
			all.each do |post|
				csv << post.attributes.values_at(*column_names)
			end
		end
	end

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			post = find_by_id(row["id"]) || new
			post.attributes = row.to_hash.slice(*Post.attribute_names())
			post.save!
		end
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
			when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
	  		when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	  		when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	  		else raise "Unknown file type: #{file.original_filename}"
  		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/No-Avatar.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :username, :password, :password_confirmation)}
	    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :avatar)}
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		Notifier.confirmation(@post).deliver
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  end

  def unprocessable
  end

  def internal_server_error
  end
end

app/controllers/export_controller.rb
class ExportController < ApplicationController
	def show
		@post = Post.find(params[:id])
		respond_to do |format|
		  format.xls
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		if params[:tag_list]
			@posts = Post.paginate(:page => params[:page], :per_page => 10).tagged_with(params[:tag_list]).order('created_at DESC').status_active
		else
			@posts = Post.paginate(:page => params[:page], :per_page => 10).order('created_at DESC').status_active
		end
		respond_to do |format|
		  format.html
		  format.csv { send_data text: @posts.to_csv }
		  format.xls #{ send_data text: @posts.to_csv(col_sep: "\t") }
		  format.js
		end
	end
	
	def import
		Post.import(params[:file])
		redirect_to root_url, notice: "Posts imported."
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body, :status))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	def list
		if params[:tag_list]
			@posts = current_user.posts.paginate(:page => params[:page], :per_page => 10).tagged_with(params[:tag_list]).order('created_at DESC')
		else
			@posts = current_user.posts.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
		end
		respond_to do |format|
		  format.html
		end
	end

	def status
		@post = Post.find(params[:id])
		if @post.status == "off"
			@post.update(:status => "active")
		else
			@post.update(:status => "off")
		end
		redirect_to list_path, notice: "Post status has changed to " + @post.status
	end

	private
		def post_params
			params.require(:post).permit(:title, :body, :tag_list, :status)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	def new
		super
	end
  def create
    @user = User.find_by_username(params[:username])
    if @user != nil
    	redirect_to root_path
    else
        super
    end
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
	def check_page
		if current_page?(root_path)
			"All Posts"
		elsif current_page?(about_path)
			"About"
		else
			link_to 'Back to All Posts', root_path
		end
	end

	def check_status_login
		if user_signed_in?
			render 'layouts/layouts_render/profile'
		else
			render 'layouts/layouts_render/login'
		end
	end

	def permit(post)
		if user_signed_in?
			if post.user.email == current_user.email
				render "posts/permit"
			else
				""	
			end
		else
			""
		end
	end

	def comment_form
		if user_signed_in?
			"<h3>Add a comment:</h3>".html_safe
			render "comments/form"
		else
			"<div class= 'alert'>
				You need sign in before add a comment
			</div>".html_safe
		end
	end

	def delete_action(comment)
		if user_signed_in?
			link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: "Are you sure?"}
		else
			""
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/export_helper.rb
module ExportHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div>
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time action"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
	<p>
		<!-- Check this function in application_helper.rb -->
		<%= delete_action(comment) %>
	</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name, :value => current_user.username, :readonly => true %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<br>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/export/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Posts">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Body</Data></Cell>
        <Cell><Data ss:Type="String">Comments</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="Number"><%= @post.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @post.title %></Data></Cell>
        <Cell><Data ss:Type="String"><%= @post.body %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= @post.comments.count %></Data></Cell>
      </Row>
    </Table>
  </Worksheet>
  <Worksheet ss:Name="Comments">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Comment</Data></Cell>
      </Row>
      <% @post.comments.each do |comment| %>
      <Row>
        <Cell><Data ss:Type="String"><%= comment.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= comment.body %></Data></Cell>
       </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%=  pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
		</p>
	<p>
	<p>
		<%= f.label :tag_list %><br>
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<%= f.label :status %>
		<%= f.radio_button :status, "active" %>
		<%= label :article_status, 'active' %>
		<%= f.radio_button :status, "off", :checked => true %>	
		<%= label :article_status, 'off' %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.cktext_area :body, :ckeditor => {:uiColor => '#72CCD4'} %>
	</p>
	<p>
		<%= f.submit %> 
	</p>
<% end %>

app/views/posts/_permit.html.erb
| <%= link_to 'Edit', edit_post_path(@post), class: "action" %>
| <%= link_to 'Delete', post_path(@post), method: :delete, data:{confirm: 'Are You Sure?'}, class: "action" %>

app/views/posts/_post.html.erb
<div class="post_wrapper">
	<h2 class="title"><%= link_to post.title, post%></h2>
	<h4 class="title">Tags : <%= post.tag_list.map { |t| link_to t, tag_list_path(t) }.join(', ').html_safe %>

	</h4>
	<p>Created By : <b><%= post.user.username %></b></p>
	<p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div id="my-posts">
	<div class="post_wrapper">
		<h2>Import Posts</h2>
		<%= form_tag import_posts_path, multipart: true do %>
			<%= file_field_tag :file %><br>
			<%= submit_tag "Import" %>
		<% end %>
	</div>
	<%= render @posts %>
</div>
<div id="infinite-scrolling"><%= will_paginate%></div>

app/views/posts/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
	$(window).off('scroll');
	$('.pagination').remove();
<% end %>

app/views/posts/list.html.erb
<div class="col-lg-12">
	<h2>My Posts</h2>
	<div class="table-responsive">
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Post</th>
					<th>Tags</th>
					<th>Submitted</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% @posts.each do |post| %>
		        	<tr>
						<td><%= post.title %></td>
						<td><%= post.tag_list.map { |t| link_to t, "#" }.join(', ').html_safe %></td>
						<td><%= time_ago_in_words(post.created_at) %> Ago </td>
						<td><%= link_to post.status, status_path(post.id), class: "action" %></td>
						<td>
							<%= link_to 'Edit', edit_post_path(post), class: "action" %>
							| <%= link_to 'Delete', post_path(post), method: :delete, data:{confirm: 'Are You Sure?'}, class: "action" %>
						</td>
					</tr>
				<% end %>
			</tbody>

		</table>
	</div>
</div>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	Download :
	<%= link_to "Excel", export_path(@post, format: "xls") %>
	<h1 class="title">
		<%= @post.title %>
	</h1>
	<h3 class="title">
		<%= social_share_button_tag(@post.title) %>
	</h3>
	<p>Tag : <%= @post.tag_list.map { |t| link_to t, tag_list_path(t) }.join(', ').html_safe %></p>
	<p>Created By : <b><i><%= @post.user.username %></i></b></p>
	<p class="date">
		<b>Submitted <%= time_ago_in_words(@post.created_at) %> Ago </b>
		
		<!-- Check this function in application_helper.rb -->
		<%= permit(@post) %>
	</p>
	<p class="body">
		<%= raw (@post.body) %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<!-- Check this function in application_helper.rb -->
		<%= comment_form %>
	</div>
</div>